tabs:
  - id: openai
    label: OpenAI
    water_ml_per_prompt: 0.32
    energy_wh_per_prompt: 0.34
    co2_g_per_wh: 0.367
    footnote:
      references:
        - anchor_id: source-1
          label: "[1]"
        - anchor_id: source-3
          label: "[3]"
      citation: "Sam Altman (2025)"
      backlink: "#results-title"
      summary: "Sam Altman (CEO von Open AI) nennt 0,34 Wh Energie und 0,00032176 Liter Wasser pro Anfrage als OpenAI-Durchschnittswerte; OpenAI macht keine Angaben zum CO₂-Verbrauch, deshalb nutzt die CO₂-Berechnung den Emissionsfaktor der U.S. Energy Information Administration (EIA) von 0,367 g CO₂ je Wh, konvertiert aus 0,81 Pfund CO₂ je kWh."
  - id: literature
    label: Literatur
    water_ml_per_prompt: 1.5
    energy_wh_per_prompt: 0.421
    co2_g_per_wh: 0.367
    footnote:
      references:
        - anchor_id: source-2
          label: "[2]"
        - anchor_id: source-3
          label: "[3]"
      citation: "GPT-4o Infrastruktur (2025); EIA FAQ (2025)"
      backlink: "#results-title"
      summary: "Eine Studie aus 2025 berechnet für einen mittellangen Prompt mit GPT-4o etwa 0,421 Wh Rechenenergie und 1,5 ml Wasser; die CO₂-Berechnung nutzt den Emissionsfaktor der U.S. Energy Information Administration (EIA) von 0,367 g CO₂ je Wh, konvertiert aus 0,81 Pfund CO₂ je kWh."
references:
  - anchor_id: source-1
    label: "[1]"
    citation: "Sam Altman (2025)"
    url: "https://blog.samaltman.com/the-gentle-singularity"
    summary: "OpenAI-CEO Sam Altman hebt in seinem Blog hervor, dass eine durchschnittliche Anfrage etwa 0,34 Wh Strom und 0,00032176 Liter Wasser benötigt."
  - anchor_id: source-2
    label: "[2]"
    citation: "Studie zum Ressourcenverbrauch von LLMs (2025)"
    url: "https://arxiv.org/pdf/2505.09598v2"
    summary: "Die Studie aus 2025 berechnet für einen definierten mittellangen GPT-4o-Prompt rund 0,421 Wh Rechenenergie und 1,5 ml Wasser."
  - anchor_id: source-3
    label: "[3]"
    citation: "EIA FAQ (2025)"
    url: "https://www.eia.gov/tools/faqs/faq.php?id=74&t=11"
    summary: "Die U.S. Energy Information Administration weist für den durchschnittlichen U.S. Strommix 0,81 Pfund CO₂ je kWh aus, was 0,367 g CO₂ je Wh entspricht."
  - anchor_id: source-4
    label: "[4]"
    citation: "EPRI White Paper (2024)"
    url: "https://www.epri.com/research/products/3002028905"
    summary: "Das gemeinnützige Electric Power Research Institute (EPRI) beziffert Trainingszeiten und Stromverbrauch von GPT-3 und GPT-4 und schätzt den KI-Energieverbrauch für Betrieb, Training und Entwicklung."
  - anchor_id: source-5
    label: "[5]"
    citation: "Studie zum Wasserverbrauch von KI Modellen (2023)"
    url: "https://arxiv.org/abs/2304.03271"
    summary: "Die Studie aus 2023 schätzt, dass das Training von GPT-3 in Microsoft-Rechenzentren in den USA rund 5.4 Millionen Liter Süßwasser verbrauchte."
  - anchor_id: source-6
    label: "[6]"
    citation: "Business Insider (2024)"
    url: "https://www.businessinsider.de/wirtschaft/chatgpt-stromverbrauch-so-lange-muesste-ein-ofen-fuer-eine-frage-laufen-laut-altmann/"
    summary: "Ein Bericht über Microsofts 20-jährigen Stromliefervertrag mit einem Kernkraftwerk in Pennsylvania zur Versorgung von KI-Rechenzentren."
  - anchor_id: source-7
    label: "[7]"
    citation: "LowCarbonPower (2025)"
    url: "https://lowcarbonpower.org/de/region/Vereinigte_Staaten"
    summary: "Die Plattform stellt die Zusammensetzung des U.S.-Strommix 2024/2025 dar."
  - anchor_id: source-8
    label: "[8]"
    citation: "NDR Info (2025)"
    url: "https://www.ndr.de/nachrichten/info/Strommix-Deutschland-Wie-ist-der-Anteil-erneuerbarer-Energien,strommix102.html"
    summary: "Die Rundfunktanstalt stellt die Zusammensetzung des deutschen Strommixes dar."
  - anchor_id: source-9
    label: "[9]"
    citation: "Fraunhofer ISE (2025)"
    url: "https://www.ise.fraunhofer.de/de/presse-und-medien/presseinformationen/2025/nettostromerzeugung-im-1-halbjahr-2025-solarstrom-europaweit-auf-dem-vormarsch.html"
    summary: "Das Forschungsinstitut analysiert die Nettostromerzeugung in Deutschland und hebt den Ausbau von Wind- und Solarenergie hervor."
  - anchor_id: source-10
    label: "[10]"
    citation: "Destatis (2025)"
    url: "https://www.destatis.de/DE/Presse/Pressemitteilungen/2025/03/PD25_091_43312.html"
    summary: "Das statistische Bundesamt stellt die Aufteilung der Stromeinspeisung in Deutschland dar, sowie die Im- und Exportzahlen des deutschen Stromhandels."
  - anchor_id: source-11
    label: "[11]"
    citation: "Umweltbundesamt (2024)"
    url: "https://www.umweltbundesamt.de/themen/co2-emissionen-pro-kilowattstunde-strom-2024"
    summary: "Das Umweltbundesamt weist für Deutschland etwa 0,283 g CO₂ je Wattstunde Strom aus."
